require_relative '../confs/config'

Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"

    config.vm.provider "virtualbox" do |v|
        v.memory = 512
        v.cpus = 1
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    config.vm.provision "shell", inline: <<-SHELL
        yum install -y net-tools
    SHELL

    config.vm.provision "file", source: "../confs/config.sh", destination: "/tmp/config.sh"
    config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/tmp/id_rsa.pub"
    config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/tmp/id_rsa"

    config.vm.define $server_name do |machine|
        machine.vm.hostname = $server_name
        machine.vm.network "private_network", ip: $server_ip
        machine.vm.provision "shell", privileged: true, path: "scripts/installS.sh"
        machine.vm.provision "shell", inline: $set_up_aliases
    end

    config.vm.define $worker_name do |machine|
        machine.vm.hostname = $worker_name
        machine.vm.network "private_network", ip: $worker_ip
        machine.vm.provision "shell", privileged: true, path: "scripts/installSW.sh"
        machine.vm.provision "shell", inline: $set_up_aliases
    end
end
