Vagrant.configure("2") do |config|

    config.vm.box = "generic/ubuntu2004"
    config.vm.provision "file", source: "../p3/confs/", destination: "/tmp/bonus/"
    config.vm.provision "file", source: "./scripts/", destination: "/tmp/bonus/"
    config.vm.box_check_update = false
    config.vm.network "forwarded_port", guest: 8888, host: 8888
    config.vm.network "forwarded_port", guest: 8082, host: 8082
    config.vm.network "forwarded_port", guest: 8083, host: 8083
    config.vm.network "forwarded_port", guest: 80, host: 80
    config.vm.network "forwarded_port", guest: 443, host: 443

    config.vm.provider "virtualbox" do |v|
        v.memory = 4096
        v.cpus = 2
    end

    config.vm.provision "shell", privileged: true, path: "scripts/install.sh"
    config.vm.provision "shell", privileged: true, path: "scripts/deploy.sh"
    config.vm.provision "shell", privileged: true, path: "scripts/start.sh", run: 'always'
end
