require_relative '../confs/config'

Vagrant.configure("2") do |config|

    config.vm.box = "centos/7"
    config.vm.provision "file", source: "./confs/", destination: "/tmp/p3/confs/"
    config.vm.provision "file", source: "./scripts/", destination: "/tmp/p3/confs/"

    config.vm.provider "virtualbox" do |v|
        v.name = "test"
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.provision "shell", privileged: true, path: "scripts/init.sh"
    config.vm.provision "shell", privileged: true, path: "scripts/run.sh"
end
